import type { ThemePreset } from "@/types/theme-types";

export const newYork: ThemePreset = {
  label: "New York",
  styles: {
    light: {
      background: "#ffffff",
      foreground: "#020817",
      card: "#ffffff",
      "card-foreground": "#020817",
      popover: "#ffffff",
      "popover-foreground": "#020817",
      primary: "#0f172a",
      "primary-foreground": "#f8fafc",
      secondary: "#f1f5f9",
      "secondary-foreground": "#0f172a",
      muted: "#f1f5f9",
      "muted-foreground": "#64748b",
      accent: "#f1f5f9",
      "accent-foreground": "#0f172a",
      destructive: "#ef4444",
      "destructive-foreground": "#f8fafc",
      border: "#e2e8f0",
      input: "#e2e8f0",
      ring: "#cbd5e1",
      "chart-1": "#0c4a6e",
      "chart-2": "#075985",
      "chart-3": "#0369a1",
      "chart-4": "#0284c7",
      "chart-5": "#0ea5e9",
      radius: "0.5rem",
      sidebar: "#f9fafb",
      "sidebar-foreground": "#020817",
      "sidebar-primary": "#0f172a",
      "sidebar-primary-foreground": "#f8fafc",
      "sidebar-accent": "#f1f5f9",
      "sidebar-accent-foreground": "#0f172a",
      "sidebar-border": "#e2e8f0",
      "sidebar-ring": "#cbd5e1",
    },
    dark: {
      background: "#020817",
      foreground: "#f8fafc",
      card: "#0f172a",
      "card-foreground": "#f8fafc",
      popover: "#0f172a",
      "popover-foreground": "#f8fafc",
      primary: "#f8fafc",
      "primary-foreground": "#0f172a",
      secondary: "#1e293b",
      "secondary-foreground": "#f8fafc",
      muted: "#1e293b",
      "muted-foreground": "#94a3b8",
      accent: "#1e293b",
      "accent-foreground": "#f8fafc",
      destructive: "#7f1d1d",
      "destructive-foreground": "#f8fafc",
      border: "#1e293b",
      input: "#1e293b",
      ring: "#475569",
      "chart-1": "#0c4a6e",
      "chart-2": "#075985",
      "chart-3": "#0369a1",
      "chart-4": "#0284c7",
      "chart-5": "#0ea5e9",
      radius: "0.5rem",
      sidebar: "#020817",
      "sidebar-foreground": "#f8fafc",
      "sidebar-primary": "#f8fafc",
      "sidebar-primary-foreground": "#0f172a",
      "sidebar-accent": "#1e293b",
      "sidebar-accent-foreground": "#f8fafc",
      "sidebar-border": "#1e293b",
      "sidebar-ring": "#475569",
    },
  },
};
