import type { ThemePreset } from "@/types/theme-types";

export const roseGold: ThemePreset = {
  label: "Rose Gold",
  styles: {
    light: {
      background: "#fbf8f9",
      foreground: "#3f3235",
      card: "#fbf8f9",
      "card-foreground": "#3f3235",
      popover: "#fbf8f9",
      "popover-foreground": "#3f3235",
      primary: "#d4649c",
      "primary-foreground": "#ffffff",
      secondary: "#f2e5eb",
      "secondary-foreground": "#d4649c",
      muted: "#f2e5eb",
      "muted-foreground": "#a18a91",
      accent: "#f2e5eb",
      "accent-foreground": "#d4649c",
      destructive: "#b33636",
      "destructive-foreground": "#ffffff",
      border: "#e8dae1",
      input: "#e8dae1",
      ring: "#d4649c",
      "chart-1": "#d4649c",
      "chart-2": "#c35084",
      "chart-3": "#b33d6c",
      "chart-4": "#a32a55",
      "chart-5": "#93173d",
      radius: "0.5rem",
      sidebar: "#f7f0f3",
      "sidebar-foreground": "#3f3235",
      "sidebar-primary": "#d4649c",
      "sidebar-primary-foreground": "#ffffff",
      "sidebar-accent": "#f2e5eb",
      "sidebar-accent-foreground": "#d4649c",
      "sidebar-border": "#e8dae1",
      "sidebar-ring": "#d4649c",
    },
    dark: {
      background: "#231c1e",
      foreground: "#f3eaee",
      card: "#2c2426",
      "card-foreground": "#f3eaee",
      popover: "#2c2426",
      "popover-foreground": "#f3eaee",
      primary: "#d4649c",
      "primary-foreground": "#ffffff",
      secondary: "#342a2d",
      "secondary-foreground": "#f3eaee",
      muted: "#342a2d",
      "muted-foreground": "#b6a5ac",
      accent: "#342a2d",
      "accent-foreground": "#f3eaee",
      destructive: "#b33636",
      "destructive-foreground": "#ffffff",
      border: "#403538",
      input: "#403538",
      ring: "#d4649c",
      "chart-1": "#d4649c",
      "chart-2": "#c35084",
      "chart-3": "#b33d6c",
      "chart-4": "#a32a55",
      "chart-5": "#93173d",
      radius: "0.5rem",
      sidebar: "#1a1517",
      "sidebar-foreground": "#f3eaee",
      "sidebar-primary": "#d4649c",
      "sidebar-primary-foreground": "#ffffff",
      "sidebar-accent": "#342a2d",
      "sidebar-accent-foreground": "#f3eaee",
      "sidebar-border": "#403538",
      "sidebar-ring": "#d4649c",
    },
  },
};
